# Generated by Django 2.0.6 on 2018-07-04 08:13

import assessment.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('course', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Int', 'Internal'), ('M', 'Main')], default=assessment.models.AssessmentType('Internal'), max_length=10)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('duration', models.DurationField()),
                ('year', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=None, to='course.Course')),
                ('faculty_id', models.ForeignKey(on_delete=None, to='faculty.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('T', 'Theory'), ('P', 'Practical')], default=assessment.models.QuestionType('Practical'), max_length=12)),
                ('text', models.TextField()),
                ('max_marks', models.PositiveSmallIntegerField()),
                ('question_order', models.PositiveSmallIntegerField()),
                ('marking_scheme', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
                ('outcome', models.ForeignKey(on_delete=None, to='course.CourseOutcomes')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=None, to='assessment.AssessmentQuestion')),
                ('student', models.ForeignKey(on_delete=None, to='student.Student')),
            ],
        ),
    ]
