# Generated by Django 2.0.6 on 2018-07-04 08:13

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('SEM_1', '1st Semester'), ('SEM_2', '2nd Semester'), ('SEM_3', '3rd Semester'), ('SEM_4', '4th Semester'), ('SEM_5', '5th Semester'), ('SEM_6', '6th Semester'), ('SEM_7', '7th Semester'), ('SEM_8', '8th Semester')], default=course.models.Semester('1st Semester'), max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=50)),
                ('max_marks', models.IntegerField()),
                ('credits', models.PositiveSmallIntegerField()),
                ('objective', models.TextField()),
                ('syllabus', models.TextField()),
                ('text_books', models.TextField()),
                ('ref_material', models.TextField()),
                ('prerequisite', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('hours', models.DurationField()),
                ('updated_on', models.DateField()),
                ('department', models.ForeignKey(on_delete=None, to='department.Department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('active', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=None, to='course.Course')),
                ('faculty', models.ForeignKey(on_delete=None, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=None, to='course.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=None, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=None, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name=[(course.models.FeedbackQuestionType('True/False'), 'True/False'), (course.models.FeedbackQuestionType('Multiple Choice'), 'Multiple Choice'), (course.models.FeedbackQuestionType('Rating'), 'Rating')])),
                ('options', models.PositiveSmallIntegerField()),
                ('quesText', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('feedback', models.ForeignKey(on_delete=None, to='course.CourseFeedback')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='question',
            field=models.ForeignKey(on_delete=None, to='course.FeedbackQuestion'),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='user',
            field=models.ForeignKey(on_delete=None, to='user.User'),
        ),
    ]
